---
- name: Install httpd
  yum:
    name: httpd
    update_cache: yes
    state: present


- name: Start httpd
  systemd:
    name: httpd
    state: "{{ httpd_state }}"
    enabled: yes

- name: Enable http fw service
  firewalld:
    service: http
    permanent: yes
    state: enabled
  notify: firewalld reload

- name: Copy index.html
  template:
    src: index.html.j2
    dest: "{{ index_path }}"
  notify: httpd reload
